spring.application.name=employee-leave-request

server.netty.connection-timeout=10s
server.netty.idle-timeout=30s

spring.r2dbc.url=r2dbc:postgresql://localhost:5432
spring.r2dbc.name=postgres
spring.r2dbc.username=postgres
spring.r2dbc.password=admin
spring.r2dbc.properties.schema=employee
spring.r2dbc.pool.max-size=10
spring.r2dbc.pool.initial-size=10

management.endpoints.web.exposure.include=health,prometheus
